server_port: "5000"
mpesa_consumer_key: "" 
mpesa_consumer_secret: "" 
mpesa_authenticate_url: "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials" 
mpesa_b2c_url: "https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest" 
mpesa_b2b_url: "https://sandbox.safaricom.co.ke/mpesa/b2b/v1/paymentrequest" 
mpesa_c2b_register_url: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl" 
mpesa_c2b_simulate_url: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/simulate" 
mpesa_account_balance_url: "https://sandbox.safaricom.co.ke/mpesa/accountbalance/v1/query" 
mpesa_transaction_status_url: "https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query" 
mpesa_reversal_url: "https://sandbox.safaricom.co.ke/mpesa/reversal/v1/request" 
lipa_na_mpesa_online_payment_url: "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest" 
lipa_na_mpesa_online_query_url: "https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query" 
mpesa_cert_filename: "support/mpesa-sandbox-cert.cer"
mpesa_shortcode: "" 
mpesa_username: ""
mpesa_initiator_password: ""
lipa_na_mpesa_online_shortcode: ""
lipa_na_mpesa_passkey: ""